baseURL: https://tweets.micahrl.com
languageCode: en-us
title: Micah R Ledbetter Tweet Archive

theme:
- github.com/mrled/twarchive

mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes: [""]
  text/formulalist:
    suffixes: ["formulae.txt"]
  text/html+tweet:
    suffixes: ["tweet.html"]

outputFormats:
  HtmlTweet:
    mediatype: text/html+tweet
    suffix: tweet.html
    isPlainText: true
    notAlternative: false

outputs:
  home:
    - HTML
  section:
    - HTML
    - HtmlTweet

Params:
  dateform: "2006-01-02"

disableKinds:
  - taxonomy
  - taxonomyTerm